# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7d2e104f1f5e89ae74341cc1665458bed2c4e410db82ebe8b20a3a66f3a2f22133219cc0dad8e411d8f8edddb42b084de7c2757cfe0fd93e5a7d208b3d8c577e

test:
  secret_key_base: f66a9d260379f2e70a48fb825781f013d8f6082eb6d4086b3234e9f07e1218d370c71d847909c10d2868207e45c08c41ae33b560c8f7122494e5bbf5fa61ad72

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
